---
name: Terragrunt
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  Terragrunt:
    uses: Valcilio/github_workflows/.github/workflows/terragrunt_prd.yaml@main
    secrets:
      TF_LOG: INFO
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}